apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-app-staging
  namespace: platform
spec:
  project: cauri
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  sources:
  - repoURL: https://github.com/demo-org-np-migration/web-app.git
    targetRevision: main
    path: chart
    helm:
      releaseName: web-app
      valueFiles:
      - $values/apps/web-app/values-staging.yaml
  - repoURL: https://github.com/demo-org-np-migration/gitops.git
    targetRevision: main
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
