apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fraud-scoring-prod
  namespace: platform
spec:
  project: cauri
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  source:
    repoURL: https://github.com/demo-org-np-migration/fraud-scoring.git
    targetRevision: main
    path: deploy/overlays/prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
