apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payments-worker-prod
  namespace: platform
spec:
  project: cauri
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  sources:
  - repoURL: https://github.com/demo-org-np-migration/payments-worker.git
    targetRevision: main
    path: chart
    helm:
      releaseName: payments-worker
      valueFiles:
      - $values/apps/payments-worker/values-prod.yaml
  - repoURL: https://github.com/demo-org-np-migration/gitops.git
    targetRevision: main
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
