image:
  tag: sha-85a3610
replicaCount: 1
env:
  SERVICE_NAME: payments-worker
  ENV: prod
  PORT: "8080"
  LOG_LEVEL: INFO
  DB_HOST: postgres.prod.svc
  DB_NAME: payments
  KAFKA_BOOTSTRAP: kafka.platform.svc:9092
  KAFKA_TOPIC_PREFIX: "prod."
  AWS_ENDPOINT_URL: http://localstack.platform.svc:4566
  AWS_REGION: us-east-1
  SQS_QUEUE_PREFIX: prod-
  JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=70"
